force-app/main/default/objects/Base_Rate_Schedule__c.object
<CustomObject>
    <description>Represents the base rate schedules for a plan family</description>
    <fields>
        <fullName>Tier_Code__c</fullName>
        <label>Tier Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 Tier</fullName>
                </value>
                <value>
                    <fullName>2 Tier</fullName>
                </value>
                <value>
                    <fullName>3 Tier</fullName>
                </value>
                <value>
                    <fullName>4 Tier</fullName>
                </value>
                <value>
                    <fullName>5 Tier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Base Rate Schedule</label>
    <nameField>
        <displayFormat>RSN-{000000000}</displayFormat>
        <label>Rate Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Base Rate Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Rate_Variant__c.object
<CustomObject>
    <description>Represents tiered base rates available for the plan family by variant code</description>
    <fields>
        <fullName>Tier_Code__c</fullName>
        <formula>TEXT(Base_Rate_Schedule__r.Tier_Code__c)</formula>
        <label>Tier Code</label>
        <type>Text</type>
    </fields>
    <label>Base Rate Variant</label>
    <nameField>
        <displayFormat>RS-{000000000}</displayFormat>
        <label>Rate Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Base Rate Variants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Plan__c.object
<CustomObject>
    <description>Final Go-To Market Predefined Or Custom Plans configured by assigning values to Plan Templates</description>
    <fields>
        <fullName>Base_Rate_Variant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Base Rate Variant</label>
        <referenceTo>Base_Rate_Variant__c</referenceTo>
        <relationshipName>Predefined_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Plan_Benefit__c.object
<CustomObject>
    <description>Represents benefit details that are part of a marketing plan</description>
    <fields>
        <fullName>Attribute_Category__c</fullName>
        <formula>Component_Attribute__r.Attribute_Category__c</formula>
        <label>Attribute Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Code__c</fullName>
        <formula>Component_Attribute__r.Attribute_Code__c</formula>
        <label>Attribute Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Display_Name__c</fullName>
        <formula>Component_Attribute__r.Attribute_Display_Name__c</formula>
        <label>Attribute Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Long_Code__c</fullName>
        <formula>Component_Attribute__r.Attribute_Long_Code__c</formula>
        <label>Attribute Long Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Value_Amount__c</fullName>
        <formula>Attribute_Value__r.Attribute_Value__c</formula>
        <label>Attribute Value Amount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQ_Disp_Sort__c</fullName>
        <description>this field is used to sort the categories when displaying in the proposal</description>
        <inlineHelpText>this field is used to sort the categories when displaying in the proposal</inlineHelpText>
        <label>CPQ Disp Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <formula>Plan_Template_Component__r.Component_Name__c</formula>
        <label>Component Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <formula>Plan_Template_Component__r.Component_Type__c</formula>
        <label>Component Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Network_Display_Name__c</fullName>
        <formula>Attribute_Value__r.In_Network_Display_Value__c</formula>
        <label>In Network Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Base_Component_Benefit__c</fullName>
        <formula>Plan_Template_Component__r.Is_Base_Component__c</formula>
        <label>Is Base Component Benefit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Key_Benefit__c</fullName>
        <formula>Component_Attribute__r.Is_Key_Benefit__c</formula>
        <label>Is Key Benefit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Rate_Impacting__c</fullName>
        <formula>Component_Attribute__r.Is_Rate_Impacting__c</formula>
        <label>Is Rate Impacting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Limits_And_Exceptions__c</fullName>
        <formula>Attribute_Value__r.Limits_And_Exceptions_Text_Area__c</formula>
        <label>Limits And Exceptions</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Name__c</fullName>
        <description>Using this field in Conga Dcoument generation</description>
        <formula>Marketing_Plan__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Marketing Plan Benefits</relationshipLabel>
        <relationshipName>Marketing_Plan_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Out_Of_Network_Display_Value__c</fullName>
        <formula>Attribute_Value__r.Out_Of_Network_Display_Value__c</formula>
        <label>Out Of Network Display Value</label>
        <type>Text</type>
    </fields>
    <label>Marketing Plan Benefit</label>
    <nameField>
        <displayFormat>MPB-{000000000}</displayFormat>
        <label>Benefit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Plan Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_Category__c</fullName>
        <label>Attribute Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Code__c</fullName>
        <label>Attribute Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Display_Name__c</fullName>
        <label>Attribute Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Long_Code__c</fullName>
        <label>Attribute Long Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Value_Amount__c</fullName>
        <label>Attribute Value Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQ_Disp_Sort__c</fullName>
        <description>this field used for sorting attribute categories in the porposal</description>
        <label>CPQ Disp Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Network_Display_Name__c</fullName>
        <label>In Network Display Name</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Base_Component_Benefit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Base Component Benefit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Key_Benefit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Key Benefit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Rate_Impacting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Rate Impacting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Limits_and_Exceptions__c</fullName>
        <label>Limits and Exceptions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Name__c</fullName>
        <formula>Parent_Quote_Line__r.Marketing_Plan__r.Name</formula>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Out_of_Network_Display_Value__c</fullName>
        <label>Out of Network Display Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Quote_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Quote Line</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Benefits</relationshipLabel>
        <relationshipName>Quote_Line_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Line Benefits</label>
    <nameField>
        <displayFormat>QLB-{0000000000}</displayFormat>
        <label>Benefit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Marketing_Plan_Name__c</fullName>
        <description>Used for Conga Document generation - Quote Template</description>
        <formula>Marketing_Plan__r.Name</formula>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Package_Code__c</fullName>
        <formula>Marketing_Plan__r.Plan_Component_Code__c</formula>
        <label>Marketing Plan Package Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link between Quote Line Item and Marketing Plan - To be Depracated for Purchaser Plan in Healthcloud GA</description>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tier_Code__c</fullName>
        <label>Tier Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 Tier</fullName>
                </value>
                <value>
                    <fullName>2 Tier</fullName>
                </value>
                <value>
                    <fullName>3 Tier</fullName>
                </value>
                <value>
                    <fullName>4 Tier</fullName>
                </value>
                <value>
                    <fullName>5 Tier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/flow_controller.cls
/**
 * Created by varun on 7/1/2019.
 */

public class flow_controller {

    @InvocableMethod(label='Set Quote Line Benefits SG')
    public static void setQuoteLineBenefitsSG(List<Quote> quotes) {
        setQuoteLineRatesSG(quotes);
        Map<Id,Id> qliToMarketingPlanIds = new Map<Id,Id>();
        Map<Id, List<Marketing_Plan_Benefit__c>> marketingPlanToBenefitMap = new Map<Id, List<Marketing_Plan_Benefit__c>>();
        List<Quote_Line_Benefit__c> qliBenefits = new List<Quote_Line_Benefit__c>();
        Set<Id> quoteIds = new Set<Id>();
        for(Quote quote : quotes){
            quoteIds.add(quote.Id);
        }
        List<QuoteLineItem> quoteLineItems = [SELECT Id, Marketing_Plan__c FROM QuoteLineItem WHERE QuoteId IN : quoteIds ];
        for(QuoteLineItem qli : quoteLineItems){
            qliToMarketingPlanIds.put(qli.Id, qli.Marketing_Plan__c);
        }
        //Create a Map of Benefits for each MarketingPlan for mapping to QLI Benefits
        for(Marketing_Plan_Benefit__c mktPlanDisplayBenefit: [SELECT Id, Marketing_Plan_Name__c,Marketing_Plan__c, Out_Of_Network_Display_Value__c,Limits_And_Exceptions__c
        ,Is_Rate_Impacting__c,Is_Key_Benefit__c, Is_Base_Component_Benefit__c, In_Network_Display_Name__c, Component_Type__c, Component_Name__c, Attribute_Value_Amount__c
        , Attribute_Long_Code__c,Attribute_Display_Name__c, Attribute_Code__c, Attribute_Category__c, CPQ_Disp_Sort__c
        FROM Marketing_Plan_Benefit__c WHERE Marketing_Plan__c IN : qliToMarketingPlanIds.values() ]) {
            List<Marketing_Plan_Benefit__c> planBenefits = marketingPlanToBenefitMap.get(mktPlanDisplayBenefit.Marketing_Plan__c);
            if (planBenefits == null ){
                planBenefits = new List<Marketing_Plan_Benefit__c>();
            }
            planBenefits.add(mktPlanDisplayBenefit);
            marketingPlanToBenefitMap.put(mktPlanDisplayBenefit.Marketing_Plan__c, planBenefits);
        }
        //Map MarketingPlanBenefits to QLI Benefits
        for(Id qliId : qliToMarketingPlanIds.keySet()){
            for(Id marketingPlanId : marketingPlanToBenefitMap.keySet()){
                for(Marketing_Plan_Benefit__c marketingPlanBenefitRec : marketingPlanToBenefitMap.get(marketingPlanId)){
                    System.debug(marketingPlanId);
                    system.debug(qliToMarketingPlanIds.get(qliId));
                    if(marketingPlanId == qliToMarketingPlanIds.get(qliId)){

                        Quote_Line_Benefit__c qliBenefit = new Quote_Line_Benefit__c(Parent_Quote_Line__c = qliId, Out_of_Network_Display_Value__c = marketingPlanBenefitRec.Out_Of_Network_Display_Value__c,
                                Limits_and_Exceptions__c = marketingPlanBenefitRec.Limits_And_Exceptions__c, Is_Rate_Impacting__c = marketingPlanBenefitRec.Is_Rate_Impacting__c,Is_Key_Benefit__c = marketingPlanBenefitRec.Is_Key_Benefit__c,
                                Is_Base_Component_Benefit__c = marketingPlanBenefitRec.Is_Base_Component_Benefit__c, In_Network_Display_Name__c = marketingPlanBenefitRec.In_Network_Display_Name__c,
                                Component_Type__c = marketingPlanBenefitRec.Component_Type__c,Component_Name__c = marketingPlanBenefitRec.Component_Name__c,Attribute_Value_Amount__c = marketingPlanBenefitRec.Attribute_Value_Amount__c,
                                Attribute_Long_Code__c = marketingPlanBenefitRec.Attribute_Long_Code__c,Attribute_Display_Name__c = marketingPlanBenefitRec.Attribute_Display_Name__c,Attribute_Code__c = marketingPlanBenefitRec.Attribute_Code__c,Attribute_Category__c= marketingPlanBenefitRec.Attribute_Category__c,
                                CPQ_Disp_Sort__c = marketingPlanBenefitRec.CPQ_Disp_Sort__c);
                        qliBenefits.add(qliBenefit);
                    }

                }
            }

        }
        system.debug(qliBenefits.size());
        insert(qliBenefits);

    }

    public static void setQuoteLineRatesSG(List<Quote> quotes) {
        Map<Id,String> qliToMarketingPlanPackageCodes = new Map<Id,String>();
        Map<String, Base_Rate_Variant__c> packageCodeToBaseRateVariant = new Map<String, Base_Rate_Variant__c>();
        List<Quote_Line_Benefit__c> qliBenefits = new List<Quote_Line_Benefit__c>();
        Set<Id> quoteIds = new Set<Id>();
        for(Quote quote : quotes){
            quoteIds.add(quote.Id);
        }
        List<QuoteLineItem> quoteLineItems = [SELECT Id, Marketing_Plan__c,Marketing_Plan_Package_Code__c, Tier_Code__c, Subscriber__c, Subscriber_And_Spouse__c, Subscriber_And_Child__c, Subscriber_And_Children__c, Subscriber_And_Family__c FROM QuoteLineItem WHERE QuoteId IN : quoteIds ];
        for(QuoteLineItem qli : quoteLineItems){
            qliToMarketingPlanPackageCodes.put(qli.Id, qli.Marketing_Plan_Package_Code__c);
        }

        //Fetch Relevant Base Rate Variants
        for (Base_Rate_Variant__c baseRateVariant : [Select Id, Tier_Code__c, Base_Rate_Schedule__c, Subscriber__c, Subscriber_And_Child__c, Subscriber_And_Children__c, Subscriber_And_Family__c, Subscriber_And_Spouse__c, Variant_Code__c
        FROM Base_Rate_Variant__c WHERE Variant_Code__c IN : qliToMarketingPlanPackageCodes.values()]){
            packageCodeToBaseRateVariant.put(baseRateVariant.Variant_Code__c, baseRateVariant);
        }

        //Map Base Rate Variants to QLI
        for(QuoteLineItem quoteLineItem : quoteLineItems){
            Base_Rate_Variant__c baseRateVariantForQLI = packageCodeToBaseRateVariant.get(qliToMarketingPlanPackageCodes.get(quoteLineItem.Id));
            if(baseRateVariantForQLI != null){
                quoteLineItem.Tier_Code__c = baseRateVariantForQLI.Tier_Code__c;
                quoteLineItem.Subscriber__c = baseRateVariantForQLI.Subscriber__c;
                quoteLineItem.Subscriber_And_Spouse__c = baseRateVariantForQLI.Subscriber_And_Spouse__c;
                quoteLineItem.Subscriber_And_Child__c = baseRateVariantForQLI.Subscriber_And_Child__c;
                quoteLineItem.Subscriber_And_Children__c = baseRateVariantForQLI.Subscriber_And_Children__c;
                quoteLineItem.Subscriber_And_Family__c = baseRateVariantForQLI.Subscriber_And_Family__c;
            }

        }
        update(quoteLineItems);

    }

    /**
   * Generic Commit which returns context object id for navigation
   *
   * commit_generic
   *
   * @param List <Object> jsonMap
   * @return List < Map < String, Object >> returnList
   */
    public static List < Map < String, Object >> commit_generic(List <Object> jsonList) {
        List < Map < String, Object >> returnList = new List < Map < String, Object >> ();
        Map<String, Object> commitEntityMap = commitListToMap(jsonList);
        String contextRecordId = tooling_controller.asNonNullString((String) commitEntityMap.get('context_record_id'));
        //For Navigation Keep Respective Object Id keep as first in response List
        returnList.add(new Map<String, Object>{
                'objectId' => contextRecordId
        });
        return returnList;
    }

    /**
   * Generic Commit which returns context object id for navigation
   *
   * commit_generic
   *
   * @param List <Object> jsonMap
   * @return List < Map < String, Object >> returnList
   */
    public static List < Map < String, Object >> create_group_quote(List <Object> jsonList) {
        List < Map < String, Object >> returnList = new List < Map < String, Object >> ();
        Map<String, Object> commitEntityMap = commitListToMap(jsonList);
        String contextRecordId = tooling_controller.asNonNullString((String) commitEntityMap.get('context_record_id'));
        //For Navigation Keep Respective Object Id keep as first in response List
        returnList.add(new Map<String, Object>{
                'objectId' => contextRecordId
        });
        return returnList;
    }


    /**
    * Converts JSON List to Object Map
    *
    * commitListToMap
    *
    * @param List<Object> jsonList
    * @return Map<String, Object>
    */
    private static Map<String, Object> commitListToMap(List<Object> jsonList){
        Map<String, Object> commitEntityMap = new Map<String, Object>();
        for (Object obj : jsonList) {
            Map <String, Object> objRecord = (Map <String, Object>) JSON.deserializeUntyped(JSON.serialize(obj));
            String objType = String.escapeSingleQuotes(tooling_controller.asNonNullString((String) objRecord.get('objectType')));
            String objName = String.escapeSingleQuotes(tooling_controller.asNonNullString((String) objRecord.get('name')));
            String dataType = String.escapeSingleQuotes(tooling_controller.asNonNullString((String) objRecord.get('dataType')));
            Object objValue = (Object) objRecord.get('value');
            if(dataType == 'SOBJECT'){
                if (objType == 'Account') {
                    //commitEntityMap.put(objName, JSON.deserialize(JSON.serialize(addFieldNamespaces(objValue)), Account.class));
                }else if(objType == 'Quote'){
                    commitEntityMap.put(objName, JSON.deserialize(JSON.serialize(tooling_controller.addFieldNamespaces(objValue)), Quote.class));
                }else if(objType =='Quote_Census__c'){
                    //commitEntityMap.put(objName, JSON.deserialize(JSON.serialize(tooling_controller.addListFieldNamespaces(objValue, false)), List<Quote_Census__c>.class));
                }else if(objType =='Quote_Line_Census__c'){
                    // system.debug(objValue);
                    //commitEntityMap.put(objName, JSON.deserialize(JSON.serialize(Tooling_Controller.addListFieldNamespaces(objValue, false)), List<Quote_Line_Census__c>.class));
                }else if(objType =='Product2'){
                    commitEntityMap.put(objName, JSON.deserialize(JSON.serialize(tooling_controller.addListFieldNamespaces(objValue, false)), List<Product2>.class));
                }
            }else if(dataType == 'STRING'){
                commitEntityMap.put(objName, tooling_controller.asNonNullString((String) objValue));
            }
        }
        return commitEntityMap;
    }
}