force-app/main/default/objects/Marketing_Plan__c.object
<CustomObject>
    <description>Final Go-To Market Predefined Or Custom Plans configured by assigning values to Plan Templates</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Family_Name__c</fullName>
        <formula>Plan_Family__r.Name</formula>
        <label>Plan Family Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Family__c</fullName>
        <label>Plan Family</label>
        <referenceTo>Plan_Family__c</referenceTo>
        <relationshipLabel>Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Template__c</fullName>
        <label>Plan Template</label>
        <referenceTo>Plan_Template__c</referenceTo>
        <relationshipLabel>Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <formula>TEXT(Plan_Family__r.Line_Of_Business__c)</formula>
        <label>Plan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Workspace</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Plan_Benefit__c.object
<CustomObject>
    <description>Represents benefit details that are part of a marketing plan</description>
    <fields>
        <fullName>Attribute_Category__c</fullName>
        <formula>Component_Attribute__r.Attribute_Category__c</formula>
        <label>Attribute Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Code__c</fullName>
        <formula>Component_Attribute__r.Attribute_Code__c</formula>
        <label>Attribute Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Display_Name__c</fullName>
        <formula>Component_Attribute__r.Attribute_Display_Name__c</formula>
        <label>Attribute Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Network_Display_Name__c</fullName>
        <formula>Attribute_Value__r.In_Network_Display_Value__c</formula>
        <label>In Network Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Network_Value__c</fullName>
        <formula>Attribute_Value__r.In_Network_Value__c</formula>
        <label>In Network Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Key_Display_Benefit__c</fullName>
        <formula>Attribute_Value__r.Attribute__r.Is_Key_Display_Benefit__c</formula>
        <label>Is Key Display Benefit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Name__c</fullName>
        <description>Using this field in Conga Dcoument generation</description>
        <formula>Marketing_Plan__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Marketing Plan Benefits</relationshipLabel>
        <relationshipName>Marketing_Plan_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Out_Of_Network_Display_Value__c</fullName>
        <formula>Attribute_Value__r.Out_Of_Network_Display_Value__c</formula>
        <label>Out Of Network Display Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Family__c</fullName>
        <formula>CASESAFEID(Marketing_Plan__r.Plan_Family__c)</formula>
        <label>Plan Family</label>
        <type>Text</type>
    </fields>
    <label>Marketing Plan Benefit</label>
    <nameField>
        <displayFormat>MPB-{000000000}</displayFormat>
        <label>Benefit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Plan Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Component__c.object
<CustomObject>
    <description>Represents a grouping of attributes or benefits of a plan family. These components are used to build plan templates</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Base_Component__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Base Component</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Family__c</fullName>
        <label>Plan Family</label>
        <referenceTo>Plan_Family__c</referenceTo>
        <relationshipLabel>Plan Components</relationshipLabel>
        <relationshipName>Plan_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Workspace</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Plan Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Family__c.object
<CustomObject>
    <description>Logical Grouping for plans with shared characteristics</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Plan_Family_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Plan Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Template__c.object
<CustomObject>
    <description>Represents a base template for a plan family which is used to build predefined or custom plans</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Family__c</fullName>
        <label>Plan Family</label>
        <referenceTo>Plan_Family__c</referenceTo>
        <relationshipLabel>Plan Templates</relationshipLabel>
        <relationshipName>Plan_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Copay Deductible</fullName>
                </value>
                <value>
                    <fullName>HDHP</fullName>
                </value>
                <value>
                    <fullName>Copay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Workspace</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Plan_Family_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Workspace</fullName>
        <default>true</default>
        <label>Workspace</label>
    </customValue>
    <customValue>
        <fullName>Pending Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <masterLabel>Plan Family Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IHA_ShoppingCartController.cls
public with sharing class IHA_ShoppingCartController {


    @AuraEnabled(Cacheable=true)
    public static IHAShoppingCartInfoWrapper getAllShoppingDetails(){
        IHAShoppingCartInfoWrapper shoppingCartInfo = new IHAShoppingCartInfoWrapper();
        List<Marketing_Plan__c> marketingPlansList = new List<Marketing_Plan__c>();
        Integer lowDeductible = 0;
        Integer highDeductible = 0;
        Map<String, String> planTypeFilter = new Map<String, String>();
        Map<String, String> metalLevelFilter = new Map<String, String>();
        Map<String, String> planFamilyFilter = new Map<String, String>();
        Map<String, Integer> deductibleLowHigh = new Map<String, Integer>();
        Map<Id,Map<String,String>> marketingPlanDisplayBenefits = new Map<Id,Map<String, String>>();
        Map<Id, List<Marketing_Plan_Benefit__c>> allMarketingPlanBenefits = new Map<Id, List<Marketing_Plan_Benefit__c>>();
        Map<Id,Boolean> isConfigurable = new Map<Id,Boolean>();

        try{
            Map<ID, Marketing_Plan__c> mktPlansMap = new Map<ID, Marketing_Plan__c>([SELECT Id, Name, Plan_Family__c, Plan_Template__c, Plan_Family_Name__c, Plan_Type__c, Effective_Date__c, Termination_Date__c, Status__c FROM Marketing_Plan__c ]);
            Map<Id, Plan_Family__c> planFamilyById = new Map<Id, Plan_Family__c> ([SELECT Id,(SELECT Id, Is_Base_Component__c FROM Plan_Components__r WHERE Is_Base_Component__c=FALSE LIMIT 1) FROM Plan_Family__c]);

            //Set Is Configurable Or Not Map
            for(Marketing_Plan__c mktPlan : mktPlansMap.values()){
                if (isConfigurable.containsKey(mktPlan.Id)){
                    //Do Nothing
                }else{
                    Plan_Family__c planFamily = planFamilyById.get(mktPlan.Plan_Family__c);
                    if(planFamily.Plan_Components__r.size() > 0){
                        isConfigurable.put(mktPlan.Id, true);
                    }else{
                        isConfigurable.put(mktPlan.Id, false);
                    }
                }
            }
            if(mktPlansMap!=null && !mktPlansMap.isEmpty()) {
                marketingPlansList = mktPlansMap.values();
            }
            shoppingCartInfo.totalMKTPlans = marketingPlansList.size();
            //Set Type & Family Filter Values
            for(Marketing_Plan__c marketingplan : mktPlansMap.values()){
                planTypeFilter.put(marketingplan.Plan_Type__c, marketingplan.Plan_Type__c);
                planFamilyFilter.put(marketingplan.Plan_Family_Name__c, marketingplan.Plan_Family_Name__c);
            }
            for(Marketing_Plan_Benefit__c mktPlanDisplayBenefit: [SELECT Id, Marketing_Plan_Name__c,Marketing_Plan__c, In_Network_Value__c, Attribute_Category__c, Attribute_Code__c, Attribute_Display_Name__c, In_Network_Display_Name__c, Out_Of_Network_Display_Value__c, Is_Key_Display_Benefit__c FROM Marketing_Plan_Benefit__c WHERE  Marketing_Plan__c IN : mktPlansMap.keySet() ORDER BY Marketing_Plan__c,Attribute_Code__c ]) {
                if (mktPlanDisplayBenefit.Is_Key_Display_Benefit__c == true){
                    if(mktPlanDisplayBenefit.Attribute_Code__c == 'DED') {
                        //Set Low and high deductible filters
                        if (Integer.valueOf(mktPlanDisplayBenefit.In_Network_Value__c) < lowDeductible) {
                            lowDeductible = Integer.valueOf(mktPlanDisplayBenefit.In_Network_Value__c);
                        }
                        if (Integer.valueOf(mktPlanDisplayBenefit.In_Network_Value__c) > highDeductible) {
                            highDeductible = Integer.valueOf(mktPlanDisplayBenefit.In_Network_Value__c);
                        }
                    }
                    //Set Key Display Benefits Map for Each of the Marketing Plans
                    if(marketingPlanDisplayBenefits.containsKey(mktPlanDisplayBenefit.Marketing_Plan__c)) {
                        Map<String, String> planDisplayBenefit = marketingPlanDisplayBenefits.get(mktPlanDisplayBenefit.Marketing_Plan__c);
                        planDisplayBenefit.put(mktPlanDisplayBenefit.Attribute_Display_Name__c, mktPlanDisplayBenefit.In_Network_Display_Name__c);
                        marketingPlanDisplayBenefits.put(mktPlanDisplayBenefit.Marketing_Plan__c,planDisplayBenefit);
                    } else {
                        Map<String, String> planDisplayBenefit = new Map<String, String>();
                        planDisplayBenefit.put(mktPlanDisplayBenefit.Attribute_Display_Name__c, mktPlanDisplayBenefit.In_Network_Display_Name__c);
                        marketingPlanDisplayBenefits.put(mktPlanDisplayBenefit.Marketing_Plan__c,planDisplayBenefit);
                    }
                }
                //Append to List of Marketing Plan Benefit for Marketing Plan
                if(allMarketingPlanBenefits.containsKey(mktPlanDisplayBenefit.Marketing_Plan__c)) {
                    List<Marketing_Plan_Benefit__c> currentPlanBenefits = allMarketingPlanBenefits.get(mktPlanDisplayBenefit.Marketing_Plan__c);
                    currentPlanBenefits.add(mktPlanDisplayBenefit);
                    allMarketingPlanBenefits.put(mktPlanDisplayBenefit.Marketing_Plan__c, currentPlanBenefits);
                }else{
                    List<Marketing_Plan_Benefit__c> currentPlanBenefits = new List<Marketing_Plan_Benefit__c>();
                    currentPlanBenefits.add(mktPlanDisplayBenefit);
                    allMarketingPlanBenefits.put(mktPlanDisplayBenefit.Marketing_Plan__c, currentPlanBenefits);
                }

            }

            deductibleLowHigh.put('Low', lowDeductible);
            deductibleLowHigh.put('High', highDeductible);
            shoppingCartInfo.isConfigurable = isConfigurable;
            shoppingCartInfo.marketingPlanDisplayBenefits = marketingPlanDisplayBenefits;
            shoppingCartInfo.planTypeFilter = planTypeFilter;
            shoppingCartInfo.planFamilyFilter = planFamilyFilter;
            shoppingCartInfo.deductibleLowHigh = deductibleLowHigh;
            shoppingCartInfo.marketingPlans = marketingPlansList;
            shoppingCartInfo.metalLevelFilter = metalLevelFilter;
            shoppingCartInfo.allMarketingPlanBenefits = allMarketingPlanBenefits;

        }
        catch(Exception ex) {
        System.debug('exception occured:::::'+ex.getMessage());
            shoppingCartInfo.errorMsg = System.Label.Internal_Error;
        }
        return shoppingCartInfo;
    }

    @AuraEnabled(cacheable=true)
    public static List<Marketing_Plan__c> getMarketingPlans(Integer limitSize, Integer offset) {
        List<Marketing_Plan__c> marketingPlansList = new List<Marketing_Plan__c>();
        try {
            marketingPlansList = [SELECT Id, Name, Plan_Family__c, Plan_Template__c, Plan_Family_Name__c, Plan_Type__c, Effective_Date__c, Termination_Date__c, Status__c FROM Marketing_Plan__c ORDER BY CreatedDate LIMIT :limitSize OFFSET: offset];
        } catch(Exception ex) {
            System.debug('exception occured:::::'+ex.getMessage());
        }
        return marketingPlansList;
    }


    //Inner class returns the ShoppingPlanBenefits
    public class IHAShoppingCartInfoWrapper {
        @AuraEnabled
        public Integer totalMKTPlans; //Total Number of Marketing Plans
        @AuraEnabled
        public Map<Id,Map<String,String>> marketingPlanDisplayBenefits; //Map of the Key Display Benefits on the card for each MarketingPlan <<MarketingPlanId>,<AttributeDisplayName,AttributeDisplayValue>>
        @AuraEnabled
        public List<Marketing_Plan__c> marketingPlans; // Offset Marketing Plans
        @AuraEnabled
        public Map<Id,List<Marketing_Plan_Benefit__c>> allMarketingPlanBenefits; //Map of All Marketing Plan Benefits By Marketing Plan Id
        @AuraEnabled
        public Map<String, String> planTypeFilter; // Plan Types Filter
        @AuraEnabled
        public Map<Id, Boolean> isConfigurable; // sets Component Configurability
        @AuraEnabled
        public Map<String, String> metalLevelFilter; // Metal Level Filter
        @AuraEnabled
        public Map<String, String> planFamilyFilter; // Metal Level Filter
        @AuraEnabled
        public Map<String, Integer> deductibleLowHigh; // Deductible High and Low Map [{'Low',0},{'High',10,000}]
        @AuraEnabled
        public String errorMsg;//error message in case there are no Marketing Plan Benefits or Exception occured.
    }

}