force-app/main/default/objects/Marketing_Plan__c.object
<CustomObject>
    <description>Final Go-To Market Predefined Or Custom Plans configured by assigning values to Plan Templates</description>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Plan_Benefit__c.object
<CustomObject>
    <description>Represents benefit details that are part of a marketing plan</description>
    <fields>
        <fullName>Attribute_Category__c</fullName>
        <formula>Component_Attribute__r.Attribute_Category__c</formula>
        <label>Attribute Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Display_Name__c</fullName>
        <formula>Component_Attribute__r.Attribute_Display_Name__c</formula>
        <label>Attribute Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Network_Display_Name__c</fullName>
        <formula>Attribute_Value__r.In_Network_Display_Value__c</formula>
        <label>In Network Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Name__c</fullName>
        <description>Using this field in Conga Dcoument generation</description>
        <formula>Marketing_Plan__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Marketing Plan Benefits</relationshipLabel>
        <relationshipName>Marketing_Plan_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Out_Of_Network_Display_Value__c</fullName>
        <formula>Attribute_Value__r.Out_Of_Network_Display_Value__c</formula>
        <label>Out Of Network Display Value</label>
        <type>Text</type>
    </fields>
    <label>Marketing Plan Benefit</label>
    <nameField>
        <displayFormat>MPB-{000000000}</displayFormat>
        <label>Benefit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Plan Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/IHA_CompareMKTPlansController.cls
public with sharing class IHA_CompareMKTPlansController {

    @AuraEnabled(cacheable=true)
    public static MKTPlanBenefitsResponseWrapper getMarketingPlanBenefits(List<String> marketingplanids) {
        MKTPlanBenefitsResponseWrapper mktPlanBenefitsResWrap = new MKTPlanBenefitsResponseWrapper();
        Map<String,List<Marketing_Plan_Benefit__c>>  attrCatToMKTPBMap = new Map<String,List<Marketing_Plan_Benefit__c>>();
        List<Marketing_Plan__c> marketingPlansList = new List<Marketing_Plan__c>();
        Map<String,List<String>> attrCatToAttrDispNameMap = new Map<String,List<String>>();
        String querySOQL = '';
        System.debug(marketingplanids.size());
        if(marketingplanids != null && marketingplanids.size() > 0){
            querySOQL = 'Select Id, Name FROM Marketing_Plan__c WHERE Id IN (\'' + String.join(marketingplanids, '\',\'') + '\')';
            system.debug(querySOQL);
        }else{
            querySOQL = 'SELECT Id, Name FROM Marketing_Plan__c LIMIT 5';
        }

        try {
            List<Marketing_Plan__c> marketingPlanList = Database.query(querySOQL);
            Map<ID, Marketing_Plan__c> mktPlansMap = new Map<ID, Marketing_Plan__c>();
            for(Marketing_Plan__c marketingPlan : marketingPlanList){
                mktPlansMap.put(marketingPlan.Id, marketingPlan);
            }
            //Map<ID, Marketing_Plan__c> mktPlansMap = new Map<ID, Marketing_Plan__c>([SELECT Id, Name FROM Marketing_Plan__c LIMIT 5]);
            if(mktPlansMap!=null && !mktPlansMap.isEmpty()) {
                for(Marketing_Plan_Benefit__c mktPlanBenefit: [SELECT Id, Marketing_Plan_Name__c, 
                                                            Attribute_Category__c, Attribute_Display_Name__c, 
                                                            In_Network_Display_Name__c, Out_Of_Network_Display_Value__c 
                                                            FROM Marketing_Plan_Benefit__c 
                                                            WHERE Marketing_Plan__c IN : mktPlansMap.keySet()]) {
                    if(attrCatToMKTPBMap.containsKey(mktPlanBenefit.Attribute_Category__c)) {
                        List<Marketing_Plan_Benefit__c> mktPlanBenefitsList = attrCatToMKTPBMap.get(mktPlanBenefit.Attribute_Category__c);
                        mktPlanBenefitsList.add(mktPlanBenefit);
                        attrCatToMKTPBMap.put(mktPlanBenefit.Attribute_Category__c,mktPlanBenefitsList);

                        //attribute category to attribute display name map.
                        if(!attrCatToAttrDispNameMap.get(mktPlanBenefit.Attribute_Category__c).contains(mktPlanBenefit.Attribute_Display_Name__c)) {
                            List<String> attrDispNameList = attrCatToAttrDispNameMap.get(mktPlanBenefit.Attribute_Category__c);
                            attrDispNameList.add(mktPlanBenefit.Attribute_Display_Name__c);
                            attrCatToAttrDispNameMap.put(mktPlanBenefit.Attribute_Category__c,attrDispNameList);
                        }
                    } else {
                        attrCatToMKTPBMap.put(mktPlanBenefit.Attribute_Category__c,new List<Marketing_Plan_Benefit__c>{mktPlanBenefit});
                        attrCatToAttrDispNameMap.put(mktPlanBenefit.Attribute_Category__c,new List<String>{mktPlanBenefit.Attribute_Display_Name__c});
                    }
                    
                    if(mktPlansMap!=null && !mktPlansMap.isEmpty()) {
                        marketingPlansList = mktPlansMap.values();
                    }                                  
                }
                mktPlanBenefitsResWrap.attrCategoryToMKTPBMap = attrCatToMKTPBMap;
                mktPlanBenefitsResWrap.attrCatToAttrDispNameMap = attrCatToAttrDispNameMap;
                mktPlanBenefitsResWrap.marketingPlans = marketingPlansList;
                //count the total Marketing Plans.
                mktPlanBenefitsResWrap.totalMKTPlans = marketingPlansList.size();
            }
            if(attrCatToMKTPBMap.isEmpty()) {
                System.debug(System.Label.No_MKT_Plan_Benefits_Available);
                mktPlanBenefitsResWrap.errorMsg = System.Label.No_MKT_Plan_Benefits_Available;
            }
        } catch(Exception ex) {
            System.debug('exception occured:::::'+ex.getMessage());
            mktPlanBenefitsResWrap.errorMsg = System.Label.Internal_Error;
        }
        return mktPlanBenefitsResWrap;
    }
    
    //Inner class returns the Marketing Plan Benefits.
    public class MKTPlanBenefitsResponseWrapper {
        @AuraEnabled
        public Map<String,List<Marketing_Plan_Benefit__c>> attrCategoryToMKTPBMap;//attribute category to MKT Plan Benefits.
        @AuraEnabled
        public Map<String,List<String>> attrCatToAttrDispNameMap;//attribute Category to attribute display name map.
        @AuraEnabled
        public List<Marketing_Plan__c> marketingPlans;//Marketing Plans
        @AuraEnabled
        public Integer totalMKTPlans;//total number of Marketing Plans
        @AuraEnabled
        public String errorMsg;//error message in case there are no Marketing Plan Benefits or Exception occured.
    }

}